### ISSUE TITLE
commit a new passage by my friend.

### ISSUE THREAD

**Issue by xieyangyuyue** [muzakiso/muzakiso.github.io#1]
《浪客剑心追忆篇》
[《浪客剑心追忆篇》是一部可称完美的作品。残酷血腥的画面，却在白梅和幕末的时代背景下讲述着剑与血的暴力美学，在圆月与夕阳照映下的影像中的日本，有一种萧瑟的美感。影片中的剑心虽然是主角，但在片中所渲染的那样充满了痛苦的时代里，虽然有极高的剑术，却只是历史洪流中微不足道的一缕。影片强烈的东方悲剧美来源于对人物环境和情绪的视觉化，影视语言纯熟到了极致。片子重点刻画了瘦小如同女子但却只能杀人的剑心，也刻画了同时具有姐姐、妻子与仇人属性的雪代巴。那在白梅香味的血雨中降临的意象真的让人无法忘记。但是，不仅是主角，配角的刻画也是淋漓尽致] ，桂先生，叛徒，甚至是结尾部分的那一点点群像的人物（例如咳血的冲田总司，还有新选组其他人等等），已经跳脱了维新派化石守旧派这样政治主题，而升华到乱世中追求美好的不同方式和选择。世界如此艰难，每天生活只有一声叹息，但人们还是在努力地追求美好，只是这过程总是伴随着悲伤与离别。
电影背景发生于十九世纪中期，独揽大权地德川幕府对外闭关锁国，对内则是苛政暴权。面对不断出现的反抗力量，幕府的做法只是对反抗力量进行清杀。一时间举国上下时局动荡、战火纷飞。
年幼的剑心在战火中失去了珍贵之人，背负着珍贵之人的的生命。为了支撑自己并且保护他人，心太拜比古清十郎为师，学习飞天御剑流。
学有所成后，剑心想要下山，从时代的苦难中保护人民。但就如比古清十郎所说:“想要改变乱世，就必须要加入一方势力，也就会被一方势力所利用。” 剑心就被桂先生理念所吸引，为了创建新时代而挥刀。相信自己污浊的血刀和牺牲的生命定能换来人人安泰的新时代。
但是剑心内心矛盾了，一条条被他取走的生命无疑又是与为弱小的人挥刀的初心所违背。陷入了被各自正义所推动的永不厌倦的厮杀，成为杀人无数的刽子手。
春观夜樱，夏望繁星，秋赏满月，冬会初雪，此等良辰美景，剑心只能感受到酒中血的腥味。还记得浪客剑心第一话中，巴的：“你真是能唤来一场血雨的人。”真的感触很大，很应剑心的现状：虽然是为新时代而杀人，但仍然改变不了杀人的事实。他矛盾的内心已经明白师傅所说：“剑是凶器，剑术是杀人术，无论用多么美丽的辞藻来修饰也改变不了这个事实。”
或许桂知道让剑心充当“疯狂正义”的急先锋会毁了他，桂请求巴成为剑心的剑鞘。在与巴的相处下，慢慢转变“守护这份日常，已经是竭尽我的全力”的珍惜当下不易的生活。          
追忆篇最令人难忘的还是那荡气回肠的爱恨情仇以及它所表现的思想高度。整个故事虽然是围绕着剑心与巴的爱情展开的，但作者却没有只局限于两个人的情爱，而是将两人的感情放大在整个社会时局中。被时代推动着的爱与恨，他们的反抗显得是多么地无力。

**Comment by muzakiso** [comment]
thanks for your passage,I have read.
